# =============================================================================
# Checkov Configuration
# =============================================================================
# This file documents security checks that are intentionally skipped and why.
# Run: checkov -d . --config-file .checkov.yaml
# =============================================================================

framework:
  - terraform

# Checks to skip with documented justifications
skip-check:
  # -----------------------------------------------------------------------------
  # Network Architecture Decisions
  # -----------------------------------------------------------------------------
  
  # CKV_AWS_130: Public subnets must have public IPs for ALB to function.
  # The ALB requires instances to have public IP addresses in public subnets.
  # This is the standard AWS architecture for internet-facing load balancers.
  - CKV_AWS_130
  
  # CKV2_AWS_12: Default security group restrictions.
  # We create explicit security groups for all resources. The default SG is unused.
  # Adding a resource to restrict it adds complexity without security benefit.
  - CKV2_AWS_12

  # -----------------------------------------------------------------------------
  # KMS Key Policy Requirements
  # -----------------------------------------------------------------------------
  
  # CKV_AWS_109, CKV_AWS_111, CKV_AWS_356 for KMS: KMS key policies must use
  # "Resource": "*" because the policy is attached to the key itself.
  # This is AWS's required pattern for KMS key policies.
  # See: https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html
  # CKV_AWS_356 also triggers for GitHub Actions read-only permissions on
  # Describe* actions which require "*" for resource discovery.
  - CKV_AWS_109
  - CKV_AWS_111
  - CKV_AWS_356

  # -----------------------------------------------------------------------------
  # Logging Bucket Limitations
  # -----------------------------------------------------------------------------
  
  # CKV_AWS_18: S3 bucket access logging would create a circular dependency
  # (logs bucket logging to itself). Server access logging for the logs bucket
  # is not enabled, but all access is through IAM and bucket policies are strict.
  - CKV_AWS_18
  
  # CKV_AWS_144: Cross-region replication for logs bucket adds cost and complexity.
  # For disaster recovery, rely on S3's built-in 99.999999999% durability.
  # Enable CRR in production if regulatory requirements mandate it.
  - CKV_AWS_144
  
  # CKV2_AWS_62: S3 event notifications are not required for the logs bucket.
  # Logs are ingested by CloudWatch Logs Insights and Athena as needed.
  - CKV2_AWS_62

  # -----------------------------------------------------------------------------
  # Secrets Manager Rotation
  # -----------------------------------------------------------------------------
  
  # CKV2_AWS_57: Automatic secret rotation requires Lambda functions and
  # additional infrastructure. For database passwords, rotation would require
  # application restarts or connection pool refresh logic.
  # Consider enabling in production with proper rotation Lambda.
  - CKV2_AWS_57

  # -----------------------------------------------------------------------------
  # Optional Enhancements (not security critical)
  # -----------------------------------------------------------------------------
  
  # CKV_AWS_252: CloudTrail SNS topic is optional. CloudWatch alarms can be
  # configured directly on CloudTrail metrics without SNS.
  - CKV_AWS_252
  
  # CKV2_AWS_10: CloudTrail to CloudWatch Logs integration is optional.
  # Logs are already stored in S3 and can be queried via Athena.
  # Enable if real-time log analysis via CloudWatch Logs Insights is needed.
  - CKV2_AWS_10

  # CKV2_AWS_5: Security group attachment warning for RDS Proxy SG.
  # The RDS Proxy security group IS attached to aws_db_proxy.app resource.
  # This appears to be a Checkov detection issue with the proxy resource type.
  - CKV2_AWS_5

  # -----------------------------------------------------------------------------
  # WAF Integration
  # -----------------------------------------------------------------------------
  
  # CKV2_AWS_28: WAF for ALB. Global Accelerator provides DDoS protection.
  # WAF adds cost and requires rule management. Enable for production if
  # additional application-layer protection is needed (SQLi, XSS, etc.).
  # To enable: add aws_wafv2_web_acl and aws_wafv2_web_acl_association
  - CKV2_AWS_28

  # -----------------------------------------------------------------------------
  # KMS Key Policies
  # -----------------------------------------------------------------------------
  
  # CKV2_AWS_64: KMS keys for db and secrets use default key policy.
  # The default policy allows the AWS account to manage the key via IAM.
  # Explicit policies are defined for the logs key which needs service access.
  - CKV2_AWS_64

# Output format
output:
  - cli
  - junitxml

# Soft fail in CI (don't block pipeline, just report)
soft-fail: true
